apiVersion: v1
kind: Service
metadata:
  name: sample-preview
spec:
  selector:
    purpose: blue-green
    project: sample
    color: green         # always points to green for QA testing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
