apiVersion: v1
kind: Service
metadata:
  name: catalogue-preview
  namespace: roboshop
spec:
  selector:
    purpose: blue-green
    project: roboshop
    color: green         # always points to green for QA testing
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
